name: Deloy Dev Aurora MySQL Cluster
run-name: ${{ github.actor }} is running Workflow
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: "Environment to deploy cluster on"
    #     type: string
    #     required: true
    #   region:
    #     description: "Region to deploy cluster on"
    #     type: string
    #     required: true        
jobs:
  Depoy-with-terraform:
    runs-on: ubuntu-22.04
    environment: AWS
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail 
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan 

      - uses: actions/manual-approval@v4
        with:
          title: "Destroy Resources"
          message: "This workflow will destroy the deployed resources"     
             
      - name: Terraform Destroy
        run: terraform destroy -auto-approve



